baseURL = "https://helpmewith.money"
languageCode = "en-us"
title = "Help Me With Money! 😱"
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm","sitemap"]

[params]
  desc = "As late-stage capitalism steadily declines, money management has become a popular topic. Let's help you handle your money."
